import { ENERGY_LABELS, getStop } from './data.js';
import { createPlan, formatMinutes, formatTimeOffset, searchStops } from './logic.js';
import { createStore } from './store.js';
import { buildTools, registerWebMcp } from './webmcp.js';

const store = createStore();
const app = document.querySelector('#app');
if (!app) throw new Error('Sidequest mount not found');

const icon = (name) => { const paths = { arrow: '<path d="M5 12h14M13 6l6 6-6 6"/>', spark: '<path d="m12 3 1.5 5.5L19 10l-5.5 1.5L12 17l-1.5-5.5L5 10l5.5-1.5L12 3ZM19 16l.5 2.5L22 19l-2.5.5L19 22l-.5-2.5L16 19l2.5-.5L19 16Z"/>', pin: '<path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>', check: '<path d="m5 12 4 4L19 6"/>', plus: '<path d="M12 5v14M5 12h14"/>', refresh: '<path d="M20 11a8 8 0 0 0-14.9-3M4 5v4h4M4 13a8 8 0 0 0 14.9 3M20 19v-4h-4"/>', lock: '<rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>' }; return `<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${paths[name]}</svg>`; };
const escapeHtml = (value) => String(value).replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' })[character] ?? character);

function appShell(state) {
  const mcpLabel = state.webmcp.mode === 'preview' ? 'WebMCP preview' : 'WebMCP ready';
  return `<a class="skip-link" href="#planner">Skip to planner</a><div class="app-shell"><aside class="sidebar"><div><a class="brand" href="/" aria-label="Sidequest home"><span class="brand-mark">s</span><span>sidequest</span></a><p class="side-note">A small plan worth leaving the house for.</p><nav class="side-nav" aria-label="Main navigation"><a class="active" href="#planner"><span class="nav-dot"></span>My Saturday</a></nav></div><div class="sidebar-bottom"><div class="how-card"><p class="eyebrow">The nice bit</p><p class="how-title">You bring the feeling. The agent handles the fiddly parts.</p><div class="how-row"><span>01</span><span>Set the shape of your window</span></div><div class="how-row"><span>02</span><span>Let the route come together</span></div><div class="how-row"><span>03</span><span>Keep what feels like you</span></div></div><div class="sidebar-foot"><span class="status-dot"></span><span>${mcpLabel}</span><span class="tool-count">${state.webmcp.toolCount} tools</span></div></div></aside><main class="main-content" id="planner" tabindex="-1"><header class="topbar"><span class="eyebrow">Personal day planner</span><span class="mcp-status" aria-live="polite"><span class="status-dot"></span>${mcpLabel}<span class="status-divider"></span>${state.webmcp.toolCount} tools live</span></header><div class="intro"><div><p class="eyebrow accent">Saturday, made small</p><h1>Make a little room<br /><em>in your day.</em></h1><p class="intro-copy">Tell us the shape of your free time. We’ll find the right amount of somewhere to go.</p></div><div class="intro-stamp"><span>${icon('spark')}</span><small>Built for<br />good detours</small></div></div>${briefCard(state)}<div class="content-grid"><section class="plan-panel" aria-live="polite">${planCard(state)}</section><aside class="agent-panel">${agentCard(state)}</aside></div><footer class="page-footer"><span>Synthetic demo collection · no accounts · no tracking</span><a href="https://webmachinelearning.github.io/webmcp/" target="_blank" rel="noreferrer">About WebMCP ${icon('arrow')}</a></footer></main></div>`;
}

function briefCard(state) { const brief = state.brief; return `<section class="brief-card" aria-labelledby="brief-heading"><div class="brief-top"><div><p class="eyebrow">Your brief</p><h2 id="brief-heading">What kind of window do you have?</h2></div><span class="brief-status">${state.plan ? `${icon('check')} Brief ready` : 'Start with a brief'}</span></div><div class="brief-fields"><label>Starting near<select data-field="start"><option ${brief.start === 'Riverside' ? 'selected' : ''}>Riverside</option><option ${brief.start === 'North Quay' ? 'selected' : ''}>North Quay</option><option ${brief.start === 'Old Market' ? 'selected' : ''}>Old Market</option></select></label><label>Time I have<select data-field="durationMinutes"><option value="60" ${brief.durationMinutes === 60 ? 'selected' : ''}>1 hour</option><option value="90" ${brief.durationMinutes === 90 ? 'selected' : ''}>90 minutes</option><option value="120" ${brief.durationMinutes === 120 ? 'selected' : ''}>2 hours</option><option value="150" ${brief.durationMinutes === 150 ? 'selected' : ''}>2½ hours</option></select></label><label>Energy<select data-field="energy"><option value="gentle" ${brief.energy === 'gentle' ? 'selected' : ''}>Gentle</option><option value="balanced" ${brief.energy === 'balanced' ? 'selected' : ''}>Balanced</option><option value="bright" ${brief.energy === 'bright' ? 'selected' : ''}>Bright</option></select></label><label>Budget<select data-field="budget"><option value="0" ${brief.budget === 0 ? 'selected' : ''}>Free only</option><option value="12" ${brief.budget === 12 ? 'selected' : ''}>Up to $12</option><option value="18" ${brief.budget === 18 ? 'selected' : ''}>Up to $18</option><option value="30" ${brief.budget === 30 ? 'selected' : ''}>Up to $30</option></select></label><label class="check-field"><input type="checkbox" data-field="stepFree" ${brief.stepFree ? 'checked' : ''}/><span class="fake-check">${icon('check')}</span><span>Keep it step-free</span></label><button class="primary-button" data-action="build-plan" aria-busy="${state.status === 'building'}" ${state.status === 'building' ? 'disabled' : ''}>${state.status === 'building' ? 'Finding your rhythm…' : 'Build my route'} ${icon('arrow')}</button></div>${state.status === 'error' ? `<div class="inline-error" role="alert">${icon('refresh')} ${escapeHtml(state.error ?? 'Something went wrong.')}</div>` : ''}</section>`; }

function savePrompt(state) { const request = state.saveRequest; if (!request) return ''; const agentRequested = request.source === 'agent'; if (state.saveApproval) return `<div class="save-prompt is-approved" role="status" aria-live="polite"><div><strong>Approved for your agent.</strong><p>“${escapeHtml(request.name)}” can now be saved by the confirmed WebMCP call.</p></div><button class="quiet-button" data-action="dismiss-save">Keep as draft ${icon('refresh')}</button></div>`; return `<div class="save-prompt" role="status" aria-live="polite"><div><strong>${agentRequested ? 'Your agent is ready to save.' : 'Ready to save this plan?'}</strong><p>${agentRequested ? 'Review the route, then approve below. Your agent still needs to finish the save.' : 'Review the route, then choose whether to keep it.'}</p></div><div class="save-prompt-actions"><button class="primary-button compact" data-action="approve-save">${agentRequested ? 'Approve for agent' : 'Approve & save'} ${icon('check')}</button><button class="quiet-button" data-action="dismiss-save">Keep as draft</button></div></div>`; }
function planCard(state) { if (state.status === 'building') return `<div class="panel-heading"><div><p class="eyebrow">The plan</p><h2>Finding your rhythm<span class="loading-dots">…</span></h2></div></div><div class="loading-state"><div class="loading-orbit"></div><p>Looking for a route that gives your time somewhere to go.</p><span>Checking ${state.brief.durationMinutes} minutes · ${ENERGY_LABELS[state.brief.energy]} energy · ${state.brief.stepFree ? 'step-free' : 'stairs okay'}</span></div>`; if (!state.plan) return `<div class="panel-heading"><div><p class="eyebrow">The plan</p><h2>Your Saturday is still blank.</h2></div></div><div class="empty-state"><div class="empty-icon">${icon('spark')}</div><p>Give us the shape of your free time and we’ll find three small moments that belong together.</p><button class="text-button" data-action="build-plan">Build a first route ${icon('arrow')}</button></div>`; const plan = state.plan; return `<div class="panel-heading"><div><p class="eyebrow">The plan</p><h2>${escapeHtml(plan.title)}</h2><p class="panel-subtitle">A little outside, a little yours.</p></div><div class="plan-meta"><span>${formatMinutes(plan.totalMinutes)}</span><span class="meta-separator">·</span><span>$${plan.totalCost}</span></div></div><div class="timeline">${plan.stops.map((planned, index) => stopCard(state, planned.stopId, planned.startMinute, planned.endMinute, index)).join('')}</div><div class="plan-bottom"><div class="plan-fit"><span class="fit-icon">${icon('check')}</span><span><strong>It fits.</strong> ${plan.totalMinutes} of ${plan.brief.durationMinutes} minutes used.</span></div><div class="plan-actions"><button class="quiet-button" data-action="reset">${icon('refresh')} Start over</button><button class="primary-button compact" data-action="request-save" ${state.saveRequest ? 'disabled' : ''}>Save this plan ${icon('arrow')}</button></div></div>${savePrompt(state)}`; }

function stopCard(state, stopId, startMinute, endMinute, index) { const stop = getStop(stopId); if (!stop) return ''; const isOpen = state.swapForStopId === stopId; const alternatives = searchStops({ category: stop.category, ...state.brief }).filter((candidate) => candidate.id !== stop.id).slice(0, 2); return `<article class="stop-block"><div class="stop-line"><div class="stop-marker ${stop.color}"><span>${String(index + 1).padStart(2, '0')}</span></div><div class="stop-connector"></div></div><div class="stop-card ${isOpen ? 'is-open' : ''}"><div class="stop-card-top"><span class="stop-time">${formatTimeOffset(startMinute)} <span>—</span> ${formatTimeOffset(endMinute)}</span><span class="stop-duration">${formatMinutes(endMinute - startMinute)}${stop.price ? ` · $${stop.price}` : ' · free'}</span></div><h3>${escapeHtml(stop.name)}</h3><p>${escapeHtml(stop.description)}</p><div class="stop-foot"><span class="location">${icon('pin')} ${escapeHtml(stop.neighborhood)}</span><button class="swap-button" data-action="toggle-swap" data-stop-id="${stop.id}">${isOpen ? 'Close' : 'Tune this stop'} ${icon(isOpen ? 'refresh' : 'plus')}</button></div>${isOpen ? `<div class="swap-picker"><div class="swap-picker-head"><span>Keep the ${stop.categoryLabel.toLowerCase()} feeling</span><span>Agent-compatible options</span></div>${alternatives.length ? alternatives.map((alternative) => `<button class="alternative" data-action="replace-stop" data-stop-id="${stop.id}" data-replacement-id="${alternative.id}"><span class="alternative-color ${alternative.color}"></span><span><strong>${escapeHtml(alternative.name)}</strong><small>${formatMinutes(alternative.durationMinutes)} · ${alternative.price ? `$${alternative.price}` : 'free'}</small></span>${icon('arrow')}</button>`).join('') : '<p class="no-alternatives">No other stops fit this brief yet.</p>'}</div>` : ''}</div></article>`; }

function agentCard(state) { const sourceLabel = state.webmcp.mode === 'native' ? 'Native WebMCP' : state.webmcp.mode === 'legacy' ? 'WebMCP API' : 'Preview mode'; const activityMarkup = state.activities.slice(0, 5).map((entry) => `<li class="activity-item"><span class="activity-badge ${entry.source}">${entry.source === 'agent' ? icon('spark') : entry.source === 'human' ? 'you' : '·'}</span><span><strong>${escapeHtml(entry.label)}</strong><small>${escapeHtml(entry.detail)}</small></span></li>`).join(''); return `<section class="agent-card" aria-labelledby="agent-heading"><div class="agent-card-top"><div><p class="eyebrow">The handoff</p><h2 id="agent-heading">Work with your agent.</h2></div><span class="agent-spark">${icon('spark')}</span></div><p class="agent-copy">Your agent can see the same brief and use five structured tools to search, draft, tune, and save — while you keep the final say.</p><div class="tool-list"><span>search stops</span><span>draft route</span><span>tune a stop</span><span>inspect plan</span><span>save with consent</span></div><div class="activity-head"><span>Recent activity</span><span class="live-label"><span class="status-dot"></span>Live</span></div><ol class="activity-list">${activityMarkup}</ol><div class="agent-callout"><div class="callout-icon">${icon('lock')}</div><div><strong>Human in the loop</strong><p>Saving always asks for a yes first. Your agent can plan; you decide.</p></div></div><button class="preview-button" data-action="preview-agent">${icon('spark')} Preview an agent handoff</button><small class="agent-footnote">${sourceLabel} · tools execute in this page</small></section>`; }

function render(state) { app.innerHTML = appShell(state); document.documentElement.dataset.appReady = 'true'; }
function readBrief() { const current = store.getState().brief; const read = (field) => document.querySelector(`[data-field="${field}"]`); const stepFree = read('stepFree'); return { start: read('start')?.value ?? current.start, durationMinutes: Number(read('durationMinutes')?.value ?? current.durationMinutes), energy: read('energy')?.value ?? current.energy, budget: Number(read('budget')?.value ?? current.budget), stepFree: stepFree ? Boolean(stepFree.checked) : current.stepFree }; }
function buildFromHuman() { if (store.getState().status === 'building') return; const brief = readBrief(); store.setBrief(brief, 'human'); store.beginBuild('human'); window.setTimeout(() => store.applyPlan(createPlan(brief), 'human'), 560); }
async function previewAgent() { const tools = buildTools(store); const inspect = tools.find((tool) => tool.name === 'sidequest.inspect_plan'); const search = tools.find((tool) => tool.name === 'sidequest.search_stops'); const draft = tools.find((tool) => tool.name === 'sidequest.draft_plan'); if (!inspect || !search || !draft) return; await inspect.execute({}); await search.execute({ category: 'quiet', energy: store.getState().brief.energy, stepFree: store.getState().brief.stepFree }); await draft.execute(store.getState().brief); }

document.body.addEventListener('click', (event) => { const button = event.target.closest('[data-action]'); if (!button || button.getAttribute('aria-disabled') === 'true') return; const action = button.dataset.action; if (action === 'build-plan') buildFromHuman(); if (action === 'reset') store.reset(); if (action === 'toggle-swap') store.toggleSwap(button.dataset.stopId ?? null); if (action === 'replace-stop' && button.dataset.stopId && button.dataset.replacementId) store.replaceStop(button.dataset.stopId, button.dataset.replacementId, 'human'); if (action === 'request-save') { const plan = store.getState().plan; if (plan) store.requestSave(plan.title, 'human'); } if (action === 'approve-save') { const request = store.getState().saveRequest; if (request && store.approveSave('human') && request.source === 'human') store.savePlan(request.name, 'human'); } if (action === 'dismiss-save') store.dismissSave('human'); if (action === 'preview-agent') void previewAgent(); });
store.subscribe(render);
render(store.getState());
void registerWebMcp(store).then((status) => store.setWebmcp(status)).catch(() => undefined);

export { escapeHtml };
